# Core
db:
  redis:
    emulate: true
    namespace: EG

#plugins:
  # express-gateway-plugin-example:
  #   param1: 'param from system.config' 

crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

# OAuth2 Settings
session:
  # storeProvider: connect-redis
  # storeOptions:
  #   host: 127.0.0.1
  #   port: 6379
  # secret: keyboard cat # replace with secure key that will be used to sign session cookie
  # resave: false
  # saveUninitialized: false
  secret: keyboard cat
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000
